# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
default: &default
  roles: 
    1: 'Normal User'
    2: 'Admin'
  category_types:
    1: 'Expenses'
    2: 'Income'
    3: 'Investment'
  payment_types:
    1: 'Cash'
    2: 'Credit Card'
    3: 'Debit Card'
    4: 'Transfer'
    5: 'Net Banking'
    6: 'EMI'
    7: 'Other'
    8: 'Cheque'
  transaction_types:
    1: 'Debit'
    2: 'Credit'
  financial_years:
    1: 'January To December' ## Default
development:
  secret_key_base: a62cbd84d33a03d053e5070e774f14824accf88e648b6b5785f63ab96ffa7fa86ef41a953e2ff62e4aa27773296903d2f9884ac6c2bfd526a37dde921031606e
  <<: *default
test:
  secret_key_base: 6145af28a0580628d8747d3a93f9487987f5feb89f43f01789407c9a472988cb4db5c2b3d518ae281702736dc7e3fce64caa227acb014987fab1f55c97b6d8a0
  <<: *default
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *default
